version: '3'
services:
  app:
    build: .
    ports:
      - "3333:3000"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
    volumes:
      - ./src:/usr/src/app/src
      - ./public:/usr/src/app/public
      - ./index.html:/usr/src/app/index.html
      - ./vite.config.js:/usr/src/app/vite.config.js
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
